# Generated by Django 2.2.13 on 2020-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('cost', models.IntegerField()),
                ('note', models.CharField(max_length=256)),
                ('bought_at', models.DateTimeField()),
            ],
        ),
    ]
